### ISSUE TITLE
GetFriendByIndex()

### ISSUE THREAD

**Issue by KevBRR** [philippj/SteamworksPy#13]
Hello, sorry if this is a stupid question. 

How would one go about adding and getting "GetFriendByIndex()" to work? On windows64

Thanks

**Comment by Gramps** [comment]
Hey there, not a stupid question at all.  I believe GetFriendByIndex is often used inside another function during a loop; to get the index number.  I don't think it is implemented yet in this wrapper.

Since I moved on to Godot Engine, I haven't given SteamworksPy as much attention.  I do, however, have an updated version that is much closer to the work I've been doing on GodotSteam.

But, to directly answer your question, you need to run GetFriendCount first to get the total number of friends, then use that number in GetFriendByIndex.  GetFriendCount _is_ actually implemented in the wrapper currently.

In a newer version of this wrapper, there should be a function that is just GetFriendsList or something similarly named that functions like so:

```
int friends = GetFriendCount( friendFlag );
if ( friends == -1) {
   friends = 0;
}
for ( int i = 0; i < friends; ++i ) { 
    CSteamID friendID = GetFriendByIndex( i, friendFlag );
    const char *friendName = GetFriendPersonaName( friendID );
    int steamID = friendSteamID.ConvertToUint64();
}
```
Though that will probably be returned as a dictionary or list instead.

**Comment by KevBRR** [comment]
In order for me to implement this method into the wrapper, what would I have to do? 

Add it under "Steam Apps" in "SteamworksPy.cpp" with the other functions, compile? 
Set the restype under "Friends functions" in steamworks.py, and add it under the class "SteamFriends" in steamworks.py? For then to be able to call it in my main py file? 

If I had to compile, would I just need to rename it to the dll that I'm using? "SteamworksPy64.dll"
I'm not very familiar with c++ at all, and if this was the case, what would I need to add in the c++ file? Maybe something close to this?

``` 
SW_PY int GetFriendByIndex(int iFriend, int iFriendFlags){
	int friends = GetFriendCount(int iFriendFlags);
	if (friends == -1) {
		friends = 0;
	}
	if (SteamFriends() == NULL){
		for (int i = 0; i < friends; ++i) {
			CSteamID friendID = GetFriendByIndex(i, iFriendFlags);
			const char *friendName = GetFriendPersonaName(friendID);
			int steamID = friendSteamID.ConvertToUint64();
			
			return SteamFriends()->GetFriendByIndex(i, iFriendFlags);

	}
}
```

**Comment by Gramps** [comment]
The easiest thing you could do is just use the already implemented GetFriendCount to find the total number of friends then you have the base to iterate with.  You can pass that to a new function, sort of like you have it but simpler:

```
SW_PY int GetFriendByIndex( int friend, int flags ){
   return SteamFriends()->GetFriendByIndex( friend, flags );
}
```

Add that to "Steam Friends", compile, add the restype and function to steamworks.py and you're almost there.  That should allow you to actually just iterate it in Python instead of tinkering with C++ to get it working.  From each output, you should have a Steam ID that you can then find the friend's name with the other already implemented GetFriendPersonaName.

I hope that makes sense!

Honestly I need to sit down and finish up my next code push to add in all the newest functionality...

**Comment by KevBRR** [comment]
Thanks you for fast response! 
Just added it, tried to compile, but I encountered these errors, same errors I encountered earlier. 

![image](https://user-images.githubusercontent.com/30986103/52192302-7a3c3300-2849-11e9-824b-72acec62e3f7.png)

**Comment by Gramps** [comment]
Yeah, wasn't sure if that'd work as a straight copy or not.  Also forgot it needs the conversion from CSteamID to a usable INT.  It also doesn't like the 'friend' variable we had.

You'd probably want something like...

```
SW_PY uint64_t GetFriendByIndex(int thisFriend, int flags){
    CSteamID friendID = SteamFriends()->GetFriendByIndex(thisFriend, flags);
    return friendID.ConvertToUint64();
}
```
See if that works better.

**Comment by KevBRR** [comment]
That did work better, thanks! I was able to compile, renamed the output DLL file to "SteamworksPy64.dll". 

Currently adding it to the steamworks.py file. Would it look something like this? 

Under "Restypes and Argtypes"

![image](https://user-images.githubusercontent.com/30986103/52193010-4b27c080-284d-11e9-89df-1338cc329554.png)

In functions, under "Steam Friends"

![image](https://user-images.githubusercontent.com/30986103/52193087-a3f75900-284d-11e9-9f24-5f1a79889647.png)

**Comment by Gramps** [comment]
Nice!  That looks about right.  You'll want to add the friendFlags thing in by default, like how it is for GetFriendCount.

**Comment by KevBRR** [comment]
I made some changes, not sure if they are correct. Thought this would work but apparently not. 

Here are the changes:
![image](https://user-images.githubusercontent.com/30986103/52194279-7c0af400-2853-11e9-923d-570ea53dfe4b.png)

This is the code I have running and the output that I am getting, however this is not my desired output, I am looking for steam IDs in the game server that I am on.  Did I do something wrong here? 
![image](https://user-images.githubusercontent.com/30986103/52194251-5aaa0800-2853-11e9-88cb-897714d2dc3e.png)

Thank you

**Comment by Gramps** [comment]
Hmm.  Since the friend flags are just hard-coded into the **_Steam.cdll.GetFriendByIndex_** call, you can change the definition for GetFriendByIndex to:

`def GetFriendByIndex( thisFriend ):`

Do you have 56 Steam friends?  If so, that print statement is at least right.  And yeah, the prints for each Steam ID seems off.  If your Steam ID shows as a long 17 digit number (I think), then it should be providing Steam ID64's.  Seems like the ID's are getting mangled somewhere.  However, the ConvertToUint64() function should have provided the right numbers.

This is the code I use in GodotSteam, which is very similar to what we are attempting to do here:

```
// Returns the Steam ID of a user.
uint64_t Steam::getFriendByIndex(int friendNum, int friendFlags){
	if(SteamFriends() == NULL){
		return 0;
	}
	CSteamID friendID = SteamFriends()->GetFriendByIndex(friendNum, friendFlags);
	return friendID.ConvertToUint64();
}
```

Almost identical actually.

**Comment by KevBRR** [comment]
Updated the c++ file to this, closer to what you just posted there. 

![image](https://user-images.githubusercontent.com/30986103/52195687-410bbf00-2859-11e9-81f7-2e30137cd147.png)

steamwork.py looks like this:
![image](https://user-images.githubusercontent.com/30986103/52195737-6993b900-2859-11e9-913a-4a3f85fa4f78.png)

restypes/argtypes

![image](https://user-images.githubusercontent.com/30986103/52195767-89c37800-2859-11e9-869f-80f1c06c77f1.png)

Tried it with that and got the same result. Could there potentially be something wrong with the restypes/argtypes?

**Comment by Gramps** [comment]
As for the restype, you have:

`Steam.cdll.GetFriendByIndex.argtypes = [c_uint64]`

And it should be:

`Steam.cdll.GetFriendByIndex.restype = int`

Try switching it and see what happens.  I have to sleep but I'll check back when I get up.  I'll also try a fresh compile on my system to see if I can figure out where it goes wrong!

**Comment by KevBRR** [comment]
Changed the restype to int, however I got the same output. Way to short for the 64-bit version of the steam id. Made the cpp identical to what you posted, compiled, did not change the output. 

Not seeing where we are going wrong here.

**Comment by Gramps** [comment]
Hmm, not sure.  I'm gonna tinker with it a bit today and see what kind of output I get.

UPDATE:  OK, the same basic function works perfectly in my GodotSteam module so there is just some weird quirk going on here.  Will report back with more!

**Comment by KevBRR** [comment]
Nice! Still looking what the reason behind it could be, however, I don't really see the problem. 

UPDATE: Did you use the exact same code as the ones I showed, or did you change something? 

![image](https://user-images.githubusercontent.com/30986103/52258420-59dea800-291f-11e9-896a-07f4a710fcea.png)

![image](https://user-images.githubusercontent.com/30986103/52258461-85fa2900-291f-11e9-9927-186152fbc795.png)

![image](https://user-images.githubusercontent.com/30986103/52258498-a629e800-291f-11e9-89af-4f71dafcecd9.png)

**Comment by Gramps** [comment]
I didn't get it working in Python, to be clear.  Just checked it against my GododSteam module for Godot Engine.  The code in the CPP file looks correct but has some weird behaviors.

For instance, the GetFriendCount gives me a totally incorrect response.  It says I have 91 friends when I really only have 56.  That function is super simple so not sure how that is that far out of whack.

The GetSteamID also gives back a Steam ID3 number instead of Steam ID64, which is what you normally want to use for things.  I think the lack of uint64_t is what does it, but I can't be sure just yet.  I had this same issue with Godot long ago and can't remember how I fixed it.

UPDATE:  Correction, friend count is actually right!  Just noticed I have 34 blocked users, which is counted in the whole.

**Comment by KevBRR** [comment]
Did you use '0x10', and where you connected to a game server when you did it? Because it takes whoever is on the game server as your "friends".

**Comment by Gramps** [comment]
I did not, I just misinterpreted the data.  I have 57 friends and 34 blocked users, which totals 91.

**Comment by Gramps** [comment]
It's still just giving me a Steam ID3 instead of a Steam ID64, which causes problems when you try to get data from certain functions.

**Comment by KevBRR** [comment]
Anyway to convert it you think?

**Comment by Gramps** [comment]
There has to be.  I fixed it before in the GodotSteam thing.  Gonna try changing the restypes in steamworks.py because the CPP is exactly the same as the GodotSteam version.

**Comment by Gramps** [comment]
Awesome.  That fixed it!  Change the restypes for GetSteamID and GetFriendByIndex to:

```
Steam.cdll.GetFriendByIndex.restype = c_uint64
Steam.cdll.GetSteamID.restype = c_uint64
```
I'll also push a code update after we get all this ironed out.  Now to figure out the GetFriendByIndex mess.

**Comment by KevBRR** [comment]
Brilliant! Works on my end, I'm getting all the different steam ID64's from the people connected to my server.  Was a pain, but we got it in the end aha, thank you very much for all your help!

UPDATE: If you still have problem with 'GetFriendByIndex', I can send you the exact code I have. 

![image](https://user-images.githubusercontent.com/30986103/52288973-70abeb80-296d-11e9-938f-f966773d357b.png)

**Comment by Gramps** [comment]
Sweet!  You're welcome!  There are a few additions though, which I will push to the repo.

You'll need to add this to the argtypes for GetFriendPersonaName:

`Steam.cdll.GetFriendPersonaName.argtypes = [c_uint64]`

This allows you to get the names of those folks.  Also in the CPP file, you need to change this:

`SW_PY const char* GetFriendPersonaName(int steamID){`

to

`SW_PY const char* GetFriendPersonaName(uint64_t steamID){`

So it'll give you the right data without crashing.  Thanks again for helping me find these bugs!  I'll make sure our changes get pushed right away.

**Comment by Gramps** [comment]
Changes are now live on the repo!

**Comment by labanau** [comment]
@KevBRR Would be possible to see the final code that you made to work? As I do want to use that function with my python program to get the steam ID connected on a server. Waiting for the response.

**Comment by Gramps** [comment]
I too am curious.  Hope to have a push update in a week with the new functions you requested.
