### ISSUE TITLE
Really need a wiki or docs.

### ISSUE THREAD

**Issue by codefather-labs** [philippj/SteamworksPy#21]
Really need a wiki or docs.
I got a lot of questions.

Like - can you start a community channel for your lib? Like Telegram channel?
Like - can i starts a game-server of CS:GO or Dota2 or any other games using you lib?

**Comment by labanau** [comment]
there is some documentation on it, it has a lot of functions missing, I am not sure if the functions are implemented but I am pretty sure that you can get done `SteamUser()->GetAuthTicket` to get the auth ticket then send it to the server and do IniateGameConnect to connect to the server, the issue is the Steamworks documentation itself is not the best.

**Comment by Gramps** [comment]
@labanau is correct.  There is a main documentation page linked in the readme of the master branch.  I may add a wiki at a later time but it would pretty much have the same information.

I am still in the process of porting functions over and not sure about game server stuff currently.

**Comment by philippj** [comment]
#53
