### ISSUE TITLE
AttributeError: function 'GetNumAchievements' not found

### ISSUE THREAD

**Issue by kennex-software** [philippj/SteamworksPy#37]
Does a game have to be released and with achievements to work?  I have one achievement setup in the Steamworks Achievements Config, but my game isn't released yet.  I'm still getting this...

I have the following:

`from steamworks import STEAMWORKS

steamworks = STEAMWORKS()
steamworks.initialize()`

And I get this error:  AttributeError: function 'GetNumAchievements' not found

I'm on Windows 10 64bit, but I put both the 32 and 64 versions of the steam_api.dll, steam_api.lib, and the SteamworksPy.dll in the root dir, the library\sdk\redist, and the redist\windows folders, just for safety.  Am I putting these files in the wrong places?

**Comment by Gramps** [comment]
Hey there!  Also responded to your e-mail.  The game does not have to be released for the functions to work but they do have to be set up in the Steamworks back-end.

Does that error happen when you try to call GetNumAchievement or just when you run the game with nothing more than the code you showed above?

If you use the pre-compiled dll from the releases tab, you don't need anything else except the steam_api64.dll and a steam_appid.txt text file with your game's app ID in it.  Those three things are all you need to test, edit, or ship.  The steam_appid.txt is most important because it tells Steam what game you are running; though this only matters if it is run **outside** of the Steam client.

**Comment by kennex-software** [comment]
I apologize for reaching out twice!  I actually got it to work.  I did not use the latest and greatest SteamworksPy64.dll, I think.  I just redownloaded it and put it into the root and the game ran right up!  I'm currently running outside of the steam client.  Thank you, Gramps!

**Comment by Gramps** [comment]
It's all good.  Important to get help when you need it.  Glad to hear you got things going and sorry I didn't have the documentation up-to-date; I'll try to get that sorted out this weekend.
